src/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Count__c</fullName>
        <label>Question Count</label>
        <summaryForeignKey>Questions__c.Review__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Review_Rating__c</fullName>
        <formula>(Total_Rating__c*100)/40</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Review Rating (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Rating__c</fullName>
        <label>Total Rating</label>
        <summarizedField>Questions__c.Rating__c</summarizedField>
        <summaryForeignKey>Questions__c.Review__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>R{000000000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/showQuestionsController.cls
public class showQuestionsController{
    public Review__c review {get;set;}
    
    string Name {get{
        return review.Name;}
        
    set;}
    public showQuestionsController(ApexPages.StandardController controller){
        review = (Review__c) controller.getRecord();    
        
    }
    
    public showQuestionsController(){
        review = [select id, name, Contact__r.name,Question_Count__c,Review_Rating__c,Total_Rating__c  from review__c where id='a00b0000007sg7h'];   
        
    }
    public PageReference listQuestions(){
        return new PageReference('/a00/o');
    }
}